name: 'Wait for Status Action'
description: 'This action fetches the status code for a specific url at a fixed interval. It runs until the status code is achieved.'
inputs:
  cmd:
    description: 'The command that should be run'
    required: true
  working_directory:
    description: "This is where the helm command will be run from"
runs:
  using: 'docker'
  image: 'Dockerfile'
   #image: "docker://ghcr.io/r26d/wait-for-status-action/wait-for-status-action:latest"
  args:
    - ${{ inputs.url }}
    - ${{ inputs.status_code}}
    - ${{ inputs.checkIntervalSeconds}}
    - ${{ inputs.maxNumberOfChecks}}
