name: 'Wait for Status Action'
description: 'This action fetches the status code for a specific url at a fixed interval. It runs until the status code is achieved.'
inputs:
  url:
    description: 'This is the url that will be checked'
    required: true
  statusCode:
    description: "This is the status code the script is looking for"
    default: 200
  checkIntervalSeconds:
    description: "How long to wait (in seconds) between requests"
    default: 10
  maxNumberOfChecks:
    description: "This is the number of checks to do before giving up"
    default: 60
runs:
  using: 'docker'
  #image: 'Dockerfile'
  image: "docker://ghcr.io/r26d/wait-for-status-action/wait-for-status-action:v0.1.3"
  args:
    - ${{ inputs.url }}
    - ${{ inputs.statusCode}}
    - ${{ inputs.checkIntervalSeconds}}
    - ${{ inputs.maxNumberOfChecks}}
